[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dotenv = "0.15.0"
gemini-rust = "1.5.1"
nu-ansi-term = "0.50.1"
reedline = "0.40.0"
rustyline = "16.0.0"
sysinfo = "0.37.2"
tokio = { version = "1.48.0", features = ["full"] }
tokio-macros = "1.8.2"
